# Generated by Django 5.1.1 on 2025-03-21 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=50)),
                ('playername', models.CharField(max_length=50)),
                ('year_of_study', models.CharField(max_length=10)),
                ('contact_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.CharField(max_length=15)),
                ('college_name', models.CharField(max_length=100)),
                ('sub_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.subevent')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=100)),
                ('year_of_study', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('contact_number', models.CharField(max_length=10)),
                ('emergency_contact', models.CharField(max_length=10)),
                ('sport', models.CharField(choices=[('cricket', 'Cricket'), ('football', 'Football'), ('volleyball', 'Volleyball'), ('kabaddi', 'Kabaddi')], default='', max_length=50)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.subevent')),
            ],
        ),
    ]
