# Generated by Django 5.1.1 on 2025-03-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='emergency_contact',
            field=models.CharField(default='0000000000', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='year_of_study',
            field=models.CharField(default='BE', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='contact_number',
            field=models.CharField(max_length=10),
        ),
    ]
