# Generated by Django 5.1.1 on 2025-04-01 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_subevent_fees'),
        ('registrationapp', '0005_alter_participant_email'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('email', 'sub_event')},
        ),
    ]
