# Generated by Django 5.1.1 on 2025-04-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0006_alter_participant_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
