# Generated by Django 5.1.1 on 2025-04-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_sportevent_sports_remove_event_required_resources_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subevent',
            name='dept',
            field=models.CharField(default='', max_length=50),
        ),
    ]
