# Generated by Django 5.1.1 on 2025-04-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_subevent_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='subevent',
            name='fees',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
