# Generated by Django 5.1.1 on 2025-04-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_subevent_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subevent',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
