# Generated by Django 5.1.1 on 2024-11-18 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('eventname', models.CharField(default='', max_length=50, unique=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=100)),
                ('year_of_study', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('contact_number', models.CharField(max_length=10)),
                ('emergency_contact', models.CharField(max_length=10)),
                ('sport', models.CharField(choices=[('cricket', 'Cricket'), ('football', 'Football'), ('volleyball', 'Volleyball'), ('kabaddi', 'Kabaddi')], default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TeamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=50)),
                ('playername', models.CharField(max_length=50)),
                ('year_of_study', models.CharField(max_length=10)),
                ('contact_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='home.eventdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(choices=[('college ground', 'College ground'), ('seminar hall', 'Seminar Hall'), ('college campus', 'College Campus')], default='College Ground', max_length=50)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='home.eventdetails')),
            ],
        ),
    ]
