# Generated by Django 5.1.1 on 2024-10-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=100)),
                ('year_of_study', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('contact_number', models.CharField(max_length=10)),
                ('emergency_contact', models.CharField(max_length=10)),
            ],
        ),
    ]
