# Generated by Django 5.1.1 on 2024-11-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=50)),
                ('playername', models.CharField(max_length=50)),
                ('year_of_study', models.CharField(max_length=10)),
                ('contact_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='registration',
            name='sport',
            field=models.CharField(choices=[('cricket', 'Cricket'), ('football', 'Football'), ('volleyball', 'Volleyball'), ('kabaddi', 'Kabaddi')], default='', max_length=50),
        ),
    ]
